---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: meliuz/jira
  description: "# jira \n"
  name: jira
spec:
  lifecycle: production
  type: service
